version: '2'

services:
  statsd:
    image: 'hopsoft/graphite-statsd:latest'
    ports:
      - "::80"
    expose:
      - "8125/udp"
    environment:
      - "SERVICE_8125_NAME=statsd-8125"
  web1:
    image: nginx:alpine
    volumes:
      - "./web1:/usr/share/nginx/html"
    ports:
      - "::80"
  web2:
    image: nginx:alpine
    volumes:
      - "./web2:/usr/share/nginx/html"
    ports:
      - "::80"
  registrator:
    image: 'gliderlabs/registrator:latest'
    command: '-internal -tags=dev consul://consul:8500'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
  syslog:
    image: 'factorish/syslog'
    command: '-t udp'
    environment:
      - "SERVICE_514_NAME=syslog-514"
      - "SERVICE_TAGS=project1"
